# Change these first
owner: beaverbuilder # Your GitHub organization or username, where this repository lives
repo: uptimes # The name of this repository

sites:
  - name: Beaver Builder
    url: https://www.wpbeaverbuilder.com/
  - name: Assistant
    url: https://assistant.pro
  - name: Assistant API
    url: https://api.assistant.pro/api/status
    __dangerous__body_degraded_if_text_missing: '{"success":true}'
  - name: Forums
    url: https://community.wpbeaverbuilder.com/
  - name: Docs
    url: https://docs.wpbeaverbuilder.com/
  - name: Demo
    url: https://demo.wpbeaverbuilder.com/
  - name: Hooks
    url: https://hooks.wpbeaverbuilder.com/
  - name: Translate
    url: https://translate.wpbeaverbuilder.com/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
 # cname: demo.upptime.js.org
  baseUrl: /uptimes
  logoUrl: https://raw.githubusercontent.com/beaverbuilder/uptimes/master/assets/upptime-icon.svg
  name: Beaver Status
 # introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
 # introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
 # navbar:
 #   - title: Status
 #     href: /
 #   - title: GitHub
 #     href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
